mage05/24/backup/shopping/goods/urls.py
#encoding: utf-8


from django.conf.urls import url

from .views import GoodsListView, GoodsDetailView, \
                    ShoppingCarCreateView, ShoppingCarNumView, \
                    ShoppingCarView, ShoppingCarDeleteView, \
                    OrderCreateView, OrderListView

app_name = 'goods'

urlpatterns = [
    url(r'^$', GoodsListView.as_view(), name="goods"),
    url(r'^(?P<pk>\d+)/$', GoodsDetailView.as_view(), name="goods_detail"),
    url(r'^add_shopping_car/$', ShoppingCarCreateView.as_view(), name="add_shopping_car"),
    url(r'^get_shopping_car_num/$', ShoppingCarNumView.as_view(), name="get_shopping_car_num"),
    url(r'^shopping_car/$', ShoppingCarView.as_view(), name="shopping_car"),
    url(r'^remove_shopping_car/$', ShoppingCarDeleteView.as_view(), name='remove_shopping_car'),
    url(r'^create_order/$', OrderCreateView.as_view(), name="create_order"),
    url(r'^orders/$', OrderListView.as_view(), name="orders"),
]

mage05/24/backup/shopping/shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^goods/', include('goods.urls')),
    url(r'^report/', include('report.urls')),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('goods:goods')), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

mage05/24/backup/shopping/goods/models.py
#encoding: utf-8
import time
from django.db import models
from django.contrib.auth import get_user_model
from account.models import UserAddress

User = get_user_model()

class Category(models.Model):
    name = models.CharField("名称", max_length=64)
    create_time = models.DateTimeField("添加时间", auto_now_add=True)
    status = models.IntegerField("状态", default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "商品分类"
        verbose_name_plural = "商品分类"


def upload_to_goods_img(instance, filename):
    return 'goods/{prefix}_{filename}.{suffix}'.format(prefix='goods', 
                filename=int(time.time() * 1000),
                suffix=filename.split('.')[-1])


class Goods(models.Model):
    category = models.ForeignKey(Category, verbose_name='分类')
    name = models.CharField("名称", max_length=64)
    price = models.FloatField("价格", default=0)
    img = models.ImageField("图片", upload_to=upload_to_goods_img)
    create_time = models.DateTimeField("添加时间")
    store = models.IntegerField("库存", default=0)
    desc = models.TextField("描述")
    status = models.IntegerField("状态", default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "商品信息"
        verbose_name_plural = "商品信息"


class GoodsExt(models.Model):
    goods  = models.ForeignKey(Goods)
    key = models.CharField("属性名", max_length=128)
    value = models.TextField("属性值")
    status = models.IntegerField("状态", default=0)

    def __str__(self):
        return "{0}:{1}".format(self.goods.name, self.key)

    class Meta:
        verbose_name = "商品扩展信息"
        verbose_name_plural = "商品扩展信息"



class ShoppingCar(models.Model):
    user = models.ForeignKey(User, verbose_name="用户")
    goods = models.ForeignKey(Goods, verbose_name="商品")
    num = models.IntegerField("商品数量", default=1)

    def __str__(self):
        return "{0}:{1}:{2}".format(self.user.username, self.goods.name, self.num)

    class Meta:
        verbose_name = "购物车"
        verbose_name_plural = "购物车"

    def total_price(self):
        return self.goods.price * self.num


class Order(models.Model):
    user = models.ForeignKey(User, verbose_name="用户")
    price = models.FloatField("总价格", default=0)
    user_address = models.ForeignKey(UserAddress, verbose_name="收货人")
    create_time = models.DateTimeField("下单时间", auto_now_add=True)
    remark = models.TextField("备注")
    pay_type = models.IntegerField("付款方式", default=0)
    pay_status = models.IntegerField("付款状态", default=0)
    update_time = models.DateTimeField(auto_now=True)
    status = models.IntegerField("状态", default=0)
    invoice_type = models.IntegerField("发票类型", default=0)
    invoice_title = models.CharField("发票抬头", max_length=256)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "订单"
        verbose_name_plural = "订单"


class GoodsBuied(models.Model):
    order = models.ForeignKey(Order, verbose_name="订单")
    price = models.FloatField("价格", default=0)
    num = models.IntegerField("数量", default=0)
    goods = models.ForeignKey(Goods, verbose_name="商品")

mage05/24/backup/shopping/goods/forms.py
#encoding: utf-8


from django import forms

from .models import Goods, Category

class GoodsAdminForm(forms.ModelForm):
    category = forms.ModelChoiceField(label="分类", queryset=Category.objects.filter(status=0))
    class Meta:
        model = Goods
        fields = '__all__'


    def clean_price(self):
        price = self.cleaned_data.get('price', 0)
        if price <= 0:
            raise forms.ValidationError('价格必须大于0')

        return price

    def clean_store(self):
        store = self.cleaned_data.get('store', 0)
        if store < 0:
            raise forms.ValidationError('库存必须大于等于0')

        return store

mage05/24/backup/shopping/goods/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView, View, TemplateView
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse

from django.db.models import Q
from django.db import transaction
from django.core.exceptions import ObjectDoesNotExist

from account.mixins import LoginRequiredMixin

from .models import Goods, ShoppingCar, Order, GoodsBuied
from account.models import UserAddress

class GoodsListView(ListView):
    template_name = 'index.html'
    model = Goods
    ordering = ['-create_time']
    paginate_by = 40

    def get_queryset(self):
        q = str(self.request.GET.get('q', '')).strip()
        queryset = super().get_queryset()
        queryset = queryset.filter(status=0)
        if q:
            queryset = queryset.filter(Q(name__icontains=q) | Q(desc__icontains=q) | Q(category__name__icontains=q))

        return queryset


class GoodsDetailView(DetailView):
    model = Goods
    template_name = 'goods/goods.html'


class ShoppingCarCreateView(LoginRequiredMixin, View):
    
    def post(self, request, *args, **kwargs):
        goods_id = request.POST.get("goods_id", 0)
        num = request.POST.get("num", 1)
        goods = Goods.objects.get(pk=goods_id)

        car = None
        try:
            car = ShoppingCar.objects.get(user=request.user, goods=goods)
            car.num += int(num)
        except ObjectDoesNotExist as e:
            car = ShoppingCar(goods=goods, num=num, user=request.user)

        car.save()

        return JsonResponse({'status' : 200, "result" : None, "errors" : []})

class ShoppingCarNumView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        cars = ShoppingCar.objects.filter(user=request.user)
        total = 0
        for car in cars:
            total += car.num

        return JsonResponse({'status' : 200, 'result' : total, "errors" : []})


class ShoppingCarView(LoginRequiredMixin, TemplateView):
    template_name = 'goods/shopping_car.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shopping_cars'] = ShoppingCar.objects.filter(user=self.request.user)
        context['user_addresses'] = UserAddress.objects.filter(user=self.request.user, status=1)
        return context


class ShoppingCarDeleteView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        shopping_car_id = request.POST.get('shopping_car', 0)
        try:
            shopping_car = ShoppingCar.objects.get(pk=shopping_car_id, user=request.user)
            shopping_car.delete()
        except ObjectDoesNotExist as e:
            pass
        return JsonResponse({'status' : 200, 'result' : None, 'errors' : None})


class OrderCreateView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        user_address = request.POST.get('user_address', 0)
        shopping_car = request.POST.getlist('shopping_car')
        
        try:
            user_address_obj = UserAddress.objects.get(pk=user_address, user=request.user, status=1)
            shopping_car_objlist = ShoppingCar.objects.filter(pk__in=shopping_car, user=request.user)
            
            price = 0
            for car in shopping_car_objlist:
                price += car.num * car.goods.price

            with transaction.atomic():
                order = Order(user=request.user, user_address=user_address_obj, price=price)
                order.save()

                for car in shopping_car_objlist:
                    goods = GoodsBuied(order=order, price=car.goods.price, num=car.num, goods=car.goods)
                    goods.save()
                    car.delete()

                #付款方式
                #
        except ObjectDoesNotExist as e:
            print(e)
            pass
        except BaseException as e:
            print(e)

        return HttpResponseRedirect(reverse('goods:orders'))


class OrderListView(LoginRequiredMixin, ListView):
    template_name = 'goods/order.html'
    model = ShoppingCar

mage05/24/backup/shopping/goods/templates/goods/goods.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block title %}商品详情{% endblock %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'goods/css/goods_detail.css' %}"/>
{% endblock %}

{% block container %}
<div class="row">
    <div class="col-xs-12">
        <div class="row product-detail">
            <div class="col-xs-12">
                <h2>{{ object.name }}</h2>
            </div>
        </div>
        <div class="row">
            <div class= "col-xs-4">
                <img id="big_img" alt="" src="{{ object.img.url }}" class="img-responsive" style="width:250px; height: 300px;">
            </div>
            <div class= "col-xs-7">
                <div class="col-xs-10">
                    <div class="row">
                        <div class="col-xs-7">
                            <strong>名称: </strong>
                            <span>{{ object.name }}</span>
                            <br/>
                            <strong>分类: </strong>
                            <span>{{ object.category.name }}</span>
                            <br/>
                            <strong>描述: </strong>
                            <span>{{ object.desc }}</span>
                            <br/>
                            <strong>上架时间: </strong>
                            <span>{{ object.create_time }}</span>
                            <br/>
                        </div>
                        <div class="col-xs-5">
                            <span class="label label-warning price">{{ object.price }}</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-7">
                            {% for ext in goods.goodsext_set.all %}
                                {% if ext.status == 0%}
                                    <strong>{{ ext.key }}: </strong>
                                    <span>{{ ext.value }}</span>
                                    <br/>
                                {% endif %}
                            {% endfor %}
                            <hr/>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-2">
                            <a href="javascript:history.back(-1);" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i> 回退 </a>
                        </div>
                        <div class="col-xs-5">
                            <form class="form-horizontal">
                                <div class="form-group">
                                    <label class="col-xs-6 control-label">数量</label>
                                    <div class="col-xs-6">
                                        <select class="form-control" id="goods_num">
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                        </select>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-xs-2">
                            <a href="javascript:void(0)" class="btn btn-primary" id="btn_add_shoppingcar"><i class="glyphicon glyphicon-shopping-cart"></i> 加入购物车</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
    jQuery(document).ready(function() {
        jQuery("#btn_add_shoppingcar").on("click", function() {
            var params = {
                "goods_id" : {{ object.pk }}, //?
                "num" : jQuery('#goods_num').val(), //?
                "csrfmiddlewaretoken" : "{{ csrf_token }}"
            };
            jQuery.post(
                "{% url 'goods:add_shopping_car' %}",
                params,
                function(result) {
                    if(result['status'] == 200) {
                        swal("添加购物车成功");
                        refresh_shopping_car();
                    }
                },
                'json');
        });
    });
{% endblock %}

mage05/24/backup/shopping/goods/templates/goods/order.html
订单列表

mage05/24/backup/shopping/goods/templates/goods/shopping_car.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block title %}购物车{% endblock %}

{% block container %}
<form action="{% url 'goods:create_order' %}" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">购物车</div>
                <table class="table">
                     <thead>
                        <tr>
                            <th></th>
                            <th colspan="2">商品</th>
                            <th>单价</th>
                            <th>数量</th>
                            <th>小计</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for shopping_car in shopping_cars %}
                            <tr id="shopping_car_{{shopping_car.pk}}">
                                <td>
                                    <input type="checkbox" name="shopping_car" value="{{ shopping_car.pk }}" checked="checked" />
                                </td>
                                <td>
                                    <a href="{% url 'goods:goods_detail' shopping_car.goods.pk %}" ><img src="{{ shopping_car.goods.img.url }}" style="width:70px; height:70px;"/></a>
                                </td>
                                <td>
                                    <a href="{% url 'goods:goods_detail' shopping_car.goods.pk %}" >{{ shopping_car.goods.name }}</a>
                                </td>
                                <td>
                                    {{ shopping_car.goods.price }}
                                </td>
                                <td>
                                    {{ shopping_car.num }}
                                </td>
                                <td>
                                    {{ shopping_car.total_price }}
                                </td>
                                <td>
                                    <a class="btn-delete" data-id="{{ shopping_car.pk }}">删除</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
           <div class="panel panel-default">
                <div class="panel-heading">收货人</div>
                <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>收货人</th>
                            <th>联系方式</th>
                            <th>固定联系方式</th>
                            <th>地址</th>
                            <th>邮箱</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user_address in user_addresses %}
                            <tr >
                                <td>
                                    <input type="radio" name="user_address" value="{{ user_address.pk }}" {% if forloop.first %}checked="checked"{% endif %}/>
                                </td>
                                <td>{{ user_address.name }}</td>
                                <td>{{ user_address.telephone }}</td>
                                <td>{{ user_address.fixedphone }}</td>
                                <td>{{ user_address.addr }}</td>
                                <td>{{ user_address.email }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">
            <input type="submit" class="btn btn-primary" value="提交订单"/>
        </div>
    </div>
</form>
{% endblock %}
{% block js %}
    jQuery(document).ready(function() {
        jQuery('a.btn-delete').on('click', function() {
            var id = jQuery(this).data('id');
            var params = {
                'shopping_car' : id,
                'csrfmiddlewaretoken' : '{{ csrf_token }}'
            };
            jQuery.post("{% url 'goods:remove_shopping_car' %}", params, function(result) {
                if(result['status'] == 200) {
                    refresh_shopping_car();
                    jQuery('tr#shopping_car_' + id).remove();
                }
            }, 'json')
        });
    });
{% endblock %}

mage05/24/backup/shopping/goods/templates/goods/shopping_car.v1.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block title %}购物车{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-12">
        <table class="table table-borderd">
            <thead>
                <tr>
                    <th></th>
                    <th>商品</th>
                    <th>单价</th>
                    <th>数量</th>
                    <th>小计</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for shopping_car in shopping_cars %}
                    <tr>
                        <td>
                            <input type="checkbox" name="shopping_car" value="{{ shopping_car.pk }}" />
                        </td>
                        <td>
                            {{ shopping_car.goods.name }}
                        </td>
                        <td>
                            <span id="shopping_car_price_{{shopping_car.pk}}" data-price="{{ shopping_car.goods.price }}"> {{ shopping_car.goods.price }}</span>
                        </td>
                        <td>
                            <span id="shopping_car_num_{{shopping_car.pk}}" data-num="{{ shopping_car.num }}">{{ shopping_car.num }}</span>
                        </td>
                        <td><span data-id="{{ shopping_car.pk }}" class="total-price"></span></td>
                        <td>
                            <a>删除</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}
{% block js %}
    jQuery(document).ready(function() {
        jQuery("span.total-price").each(function() {
            var id = jQuery(this).data('id');
            var num = jQuery('span#shopping_car_num_' + id).data('num');
            var price = jQuery('span#shopping_car_price_' + id).data('price');
            console.log([num, price])
            jQuery(this).text(Number(num) * Number(price));
        });
    });
{% endblock %}