mage05/13/messages/messages/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^online/', include('online.urls', namespace='online')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^$', RedirectView.as_view(url='/user/require_login')),
]

mage05/13/messages/online/urls.py
#encoding: utf-8

from django.conf.urls import url

from . import views

urlpatterns = [
   url(r'^$', views.index, name='index'),
   url(r'^create/$', views.create, name='create'),
   url(r'^save/$', views.save, name='save'), 

]

mage05/13/messages/user/urls.py
#encoding: utf-8
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^require_login/', views.require_login, name='require_login'),
    url(r'^login/', views.login, name='login'),
    url(r'^list_user/', views.list_user, name='list_user'),
    url(r'^delete_user/', views.delete_user, name='delete_user'),
    url(r'^create_user/', views.create_user, name='create_user'),
    url(r'^save_user/', views.save_user, name='save_user'),
    url(r'^view_user/', views.view_user, name='view_user'),
    url(r'^modify_user/', views.modify_user, name='modify_user'),
    url(r'^logout/', views.logout, name='logout'),

]

mage05/13/messages/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}Django学习{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" />
        {% block links %}{% endblock %}
        <style type="text/css">
            body {
                padding-top: 70px;
            }
            div.nav-slider {
                position: fixed;
                top: 50px;
                bottom: 0px;
                overflow-y: auto;
                background-color: #eee;
                padding-top:20px;
                padding-bottom: 20px;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">我的Django项目</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'user:logout' %}">退出登录</a></li>
                    </ul>
                    <p class="navbar-text navbar-right">欢迎 {{request.session.user.username}}, </p>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2 nav-slider">
                    <ul class="nav nav-pills nav-stacked">
                      <li role="presentation" {% block nav_user %}{% endblock %}><a href="{% url 'user:list_user'%}">用户管理</a></li>
                      <li role="presentation" {% block nav_online %}{% endblock %}><a href="{% url 'online:index'%}">留言板</a></li>
                    </ul>
                </div>
                <div class="col-md-10 col-md-offset-2">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>