mage05/19/shopping/account/urls.py
#encoding: utf-8


from django.conf.urls import url

from .views import RegisterView, ActiveView, \
                    LoginView, LogoutView, \
                    ResetPasswordView, ResetPasswordConfirmView, \
                    ModifyPasswordView, ChangePasswordView, \
                    UserExtBaseView, UserExtAvatarView,\
                    UserAddressListView, UserAddressCreateView, UserAddressDeleteView, UserAddressUpdateView, \
                    TestView

app_name = 'account'


urlpatterns = [
    url(r'^register/', RegisterView.as_view(), name="register"),
    url(r'^active/', ActiveView.as_view(), name="active"),
    url(r'^login/', LoginView.as_view(), name="login"),
    url(r'^logout/', LogoutView.as_view(), name="logout"),
    url(r'^modify_password/', ModifyPasswordView.as_view(), name="modify_password"),
    url(r'^reset_password/', ResetPasswordView.as_view(), name="reset_password"),
    url(r'^reset_password_confirm/', ResetPasswordConfirmView.as_view(), name="reset_password_confirm"),
    url(r'^change_password/', ChangePasswordView.as_view(), name="change_password"),
    url(r'^user_ext_base/', UserExtBaseView.as_view(), name="user_ext_base"),
    url(r'^user_ext_avatar/', UserExtAvatarView.as_view(), name="user_ext_avatar"),
    url(r'^user_address/$', UserAddressListView.as_view(), name="user_addresses"),
    url(r'^user_address/create/$', UserAddressCreateView.as_view(), name="create_user_address"),
    url(r'^test/(?P<pk>\d+)/(?P<b>\d+)/$', TestView.as_view(), name="test"), 
    url(r'^user_address/delete/(?P<pk>\d+)/$', UserAddressDeleteView.as_view(), name="delete_user_address"), 
    url(r'^user_address/update/(?P<pk>\d+)/$', UserAddressUpdateView.as_view(), name="update_user_address"), 



]


mage05/19/shopping/goods/urls.py
#encoding: utf-8


from django.conf.urls import url

app_name = 'goods'

urlpatterns = [

]

mage05/19/shopping/shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static  

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^goods/', include('goods.urls')),
    url(r'^report/', include('report.urls')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

mage05/19/shopping/templates/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="css/bootstrap.css"/>
<link rel="stylesheet" type="text/css" href="css/navbar.css"/>
<link rel="stylesheet" type="text/css" href="css/sticky-footer.css"/>
<link rel="stylesheet" type="text/css" href="css/product.css"/>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/bootstrap.js"></script>
<title>bootstrap test</title>
<script type="text/javascript">
	$(document).ready(function(){
		$('.img-thumbnail a').hover(function(e){
			var big_src = $(this).attr('big');
			$('#big_img').attr('src', big_src);
		});
	});
</script>
</head>
<body>
<div id="wrap">
	<nav class="navbar navbar-default" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Home</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li class="active"><a href="#">Diamonds</a></li>
					<li><a href="#">Engagement Rings</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Wedding<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li><a href="#">Separated link</a></li>
							<li class="divider"></li>
							<li><a href="#">One more separated link</a></li>
						</ul>
					</li>
				</ul>
				<form class="navbar-form navbar-left" role="search">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>
				<ul class="nav navbar-nav navbar-right">
					<li><a data-toggle="modal" href="#login" data-target="#login">Login</a></li>
					<li><a data-toggle="modal" href="#register" data-target="#register">Register</a></li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<div class="row product-detail">
					<div class="col-xs-12">
						<h2>Product name</h2>
					</div>
				</div>
				<div class="row">
					<div class= "col-xs-4">
						<img id="big_img" alt="" src="http://wbpreview.com/previews/WB0BMF1K5/img/product2.jpg" class="img-responsive">
					</div>
					<div class="col-xs-1">
						<div class="row">
							<div class="img-thumbnail" onfocus="alert('')">
								<a href="" big="http://wbpreview.com/previews/WB0BMF1K5/img/product2.jpg">
									<img src="http://wbpreview.com/previews/WB0BMF1K5/img/product2.jpg" style="width:100%;" onclick="alert(this.src)"/>
								</a>
							</div>
						</div>
						<div class="row">
							<div class="img-thumbnail">
								<a href="" big="https://apps.bigbase.nl/templates/data/web/5001/img/product_01.jpg">
									<img src="https://apps.bigbase.nl/templates/data/web/5001/img/product_01.jpg" style="width:100%;"/>
								</a>
							</div>
						</div>
						<div class="row">
							<div class="img-thumbnail">
								<a href="" big="https://apps.bigbase.nl/templates/data/web/5001/img/product_02.jpg">
									<img src="https://apps.bigbase.nl/templates/data/web/5001/img/product_02.jpg" style="width:100%;"/>
								</a>
							</div>
						</div>
						<div class="row">
							<div class="img-thumbnail">
								<a href="" big="https://apps.bigbase.nl/templates/data/web/5001/img/product_02b.jpg">
									<img src="https://apps.bigbase.nl/templates/data/web/5001/img/product_02b.jpg" style="width:100%;"/>
								</a>
							</div>
						</div>
					</div>
					<div class= "col-xs-7">
						<div class="col-xs-7">
							<div class="row">
								<div class="col-xs-7">
									<strong>Brand:</strong>
									<span>Squeezer</span>
									<br/>
									<strong>Model:</strong>
									<span>Squeezer</span>
									<br/>
									<strong>Size:</strong>
									<span>7</span>
									<br/>
									<strong>Color</strong>
									<span>Yellow</span>
									<br/>
									<strong>Quality:</strong>
									<span>new</span>
									<br/>
								</div>
								<div class="col-xs-5">
									<span class="label label-warning price">$ 0,50</span>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-7">
									<br/>
									<h3>Description</h3>
									<p>
										Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean rhoncus, nisl nec volutpat pretium, tellus lectus 
										condimentum leo, non facilisis tortor sapien a lectus.
									</p>
									<hr/>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-3">
									<a href="products.html" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i> Back</a>
								</div>
								<div class="col-xs-7">
									<form class="form-horizontal">
										<div class="form-group">
											<label class="col-xs-3 control-label">Count</label>
											<div class="col-xs-4">
												<select class="form-control">
													<option value="1">1</option>
													<option value="2">2</option>
													<option value="3">3</option>
													<option value="4">4</option>
													<option value="5">5</option>
												</select>
											</div>
										</div>
									</form>
								</div>
								<div class="col-xs-2">
									<a href="order.html" class="btn btn-primary"><i class="glyphicon glyphicon-shopping-cart"></i> Order now</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div id="footer">
	<div class="container">
		<p class="text-muted credit" align="center">©Copyright 2013 Bootply | All rights reserved. </p>
	</div>
</div>

<div class="modal" id="login">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4>Sign in</h4>
			</div>
			<div class="modal-body">
				<form class="form-horizontal" role="form" action='/user/login' method="post" name="loginForm">
					<div class="form-group">
					<label for="email" class="col-xs-4 control-label">Email</label>
					<div class="col-xs-6">
						<input type="text" class="form-control" name="email" id="email" placeholder="Email" value="">
					</div>
					</div>
					<div class="form-group">
					<label for="password" class="col-xs-4 control-label">Password</label>
					<div class="col-xs-6">
						<input type="password" class="form-control" name="password" id="password" placeholder="Password" value="">
					</div>
					</div>
					<div class="form-group">
					<div class="col-xs-offset-4 col-xs-10">
					<button type="submit" class="btn btn-primary">Login</button>
					</div>
					</div>
				</form>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->	

<div class="modal" id="register">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4>Create Account</h4>
			</div>
			<div class="modal-body">
				<form class="form-horizontal" role="form" action='/user/register' method="post" name="registerForm">
					<div class="form-group">
						<label for="userName" class="col-xs-4 control-label">Username</label>
						<div class="col-xs-6">
							<input type="text" class="form-control" name="userName" id="userName" placeholder="Username" value="">
						</div>
					</div>
					<div class="form-group">
						<label for="password" class="col-xs-4 control-label">Password</label>
						<div class="col-xs-6">
							<input type="password" class="form-control" name="password" id="password" placeholder="Password" value="">
						</div>
					</div>
					<div class="form-group">
						<label for="password2" class="col-xs-4 control-label">Confirm Password</label>
						<div class="col-xs-6">
							<input type="password" class="form-control" name="password2" id="password2" placeholder="Confirm Password" value="">
						</div>
					</div>
					
					<div class="form-group">
						<div class="col-xs-offset-4 col-xs-10">
							<button type="submit" class="btn btn-primary">Create Account</button>
						</div>
					</div>
				</form>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->	

</body>
</html>

mage05/19/shopping/templates/index.html
{% extends "layout.html" %}

{% block container %}
<div class="row">
	{% if messages %}
	    {% for message in messages %}
			{% if message.tags == 'info' %}
				<div class="alert alert-success alert-dismissible" role="alert">
			{% else %}
				<div class="alert alert-danger alert-dismissible" role="alert">
			{% endif %}
			  		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			  		{{ message }}
  				</div>
	    {% endfor %}
	{% endif %}
</div>
<div class="row">
	<div class="col-xs-6 col-md-3">
		<a class="thumbnail" href="detail.html">
			<img alt="" src="http://wbpreview.com/previews/WB0BMF1K5/img/product2.jpg" class="img-responsive">
		</a>
		<div class="panel-title text-center">
			<a href="single-item.html">HTC One V</a>
		</div>
		<div class="text-center">
			<h1 class="badge">Price: $50.00</h1>
		</div>
	</div>
</div>
{% endblock %}

mage05/19/shopping/templates/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<title>{% block title %}KK的商城{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/sticky-footer.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'sweetalert/dist/sweetalert.css' %}"/>
        {% block links %}{% endblock %}
        {% block style %}{% endblock %}
	</head>
<body>
	<div id="wrap">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/">KK的商城</a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li class="active"><a href="#">Diamonds</a></li>
						<li><a href="#">Engagement Rings</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Wedding<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li class="divider"></li>
								<li><a href="#">Separated link</a></li>
								<li class="divider"></li>
								<li><a href="#">One more separated link</a></li>
							</ul>
						</li>
					</ul>
					<form class="navbar-form navbar-left" role="search">
						<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
						</div>
						<button type="submit" class="btn btn-default">Submit</button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						{% if request.user.is_authenticated and not request.user.is_staff %}
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
								{{ request.user.userext.nickname_text }}
								<b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'account:user_ext_base' %}">用户信息</a></li>
								<li><a href="{% url 'account:user_addresses' %}">收获地址</a></li>
								<li class="divider"></li>
								<li><a data-toggle="modal" data-target="#dialog_password" data-backdrop="static">修改密码</a></li>
								<li class="divider"></li>
								<li><a href="{% url 'account:logout' %}">退出</a></li>
							</ul>
						</li>
						{% else %}
							<li><a data-toggle="modal" data-target="#dialog_login" data-backdrop="static">登录</a></li>
							<li><a data-toggle="modal" data-target="#dialog_register" data-backdrop="static">注册</a></li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">
			{% block container %}{% endblock %}
		</div>
	</div>
	<div id="footer">
		<div class="container">
			<p class="text-muted credit" align="center">©Copyright 2013 Bootply | All rights reserved. </p>
		</div>
	</div>
	<div class="modal" id="dialog_login">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4>用户登录</h4>
				</div>
				<div class="modal-body">
					<form class="form-horizontal" role="form" method="post" id="form_login">
						{% csrf_token %}
						<div class="form-group">
							<label for="username" class="col-xs-4 control-label">用户名/邮箱</label>
							<div class="col-xs-6">
								<input type="text" class="form-control" name="username" id="username" placeholder="用户名/邮箱" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="password" class="col-xs-4 control-label">密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="password" id="password" placeholder="密码" value="">
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-offset-4 col-xs-10">
								<button type="button" class="btn btn-primary" id="btn_login">登录</button>
								<button type="button" class="btn btn-link" id="btn_reset_password">忘记密码</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="modal" id="dialog_register">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4>用户注册</h4>
				</div>
				<div class="modal-body">
					<form class="form-horizontal" role="form" method="post" id="form_register">
						{% csrf_token %}
						<div class="form-group">
							<label for="username" class="col-xs-4 control-label">用户名</label>
							<div class="col-xs-6">
								<input type="text" class="form-control" name="username" id="username" placeholder="用户名" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="email" class="col-xs-4 control-label">邮箱</label>
							<div class="col-xs-6">
								<input type="text" class="form-control" name="email" id="email" placeholder="邮箱" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="password" class="col-xs-4 control-label">密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="password" id="password" placeholder="密码" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="password2" class="col-xs-4 control-label">确认密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="password2" id="password2" placeholder="确认密码" value="">
							</div>
						</div>

						<div class="form-group">
							<div class="col-xs-offset-4 col-xs-10">
								<button type="button" class="btn btn-primary" id="btn_register">注册</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class="modal" id="dialog_password">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4>修改密码</h4>
				</div>
				<div class="modal-body">
					<form class="form-horizontal" role="form" method="post" id="form_password">
						{% csrf_token %}
						<div class="form-group">
							<label for="old_password" class="col-xs-4 control-label">原密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="old_password" id="old_password" placeholder="原密码" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="password" class="col-xs-4 control-label">新密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="password" id="password" placeholder="密码" value="">
							</div>
						</div>
						<div class="form-group">
							<label for="password2" class="col-xs-4 control-label">确认密码</label>
							<div class="col-xs-6">
								<input type="password" class="form-control" name="password2" id="password2" placeholder="确认密码" value="">
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-offset-4 col-xs-10">
								<button type="button" class="btn btn-primary" id="btn_password">确定</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
    {% block dialog %}{% endblock %}
	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
	<script type="text/javascript" src="{% static 'sweetalert/dist/sweetalert.min.js' %}"></script>
    {% block script %}{% endblock %}
	<script type="text/javascript">
		jQuery(document).ready(function() {
			jQuery('#btn_register').on('click', function() {
				var params = jQuery('#form_register').serializeArray();
				jQuery.post("{% url 'account:register' %}", params, function(data) {
					if(data['status'] == 200) {
						jQuery('#dialog_register').modal('hide');
						swal({
							title: "注册成功",
							text: "请查收邮箱进行用户激活",
							type: "success",
							confirmButtonText: "确定"
						});
					} else if(data['status'] == 400) {
						var errors = [];
						jQuery.each(data['errors'], function(key, value) {
							errors.push(value[0]['message']);
						});
						swal({
							title: "验证失败",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if(data['status'] == 401) {
						var errors = data['errors'] || [];
						swal({
							title: "用户未登录",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if (data['status'] == 500) {
						var errors = data['errors'] || [];
						swal({
							title: "服务器错误",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else {

					}
				}, 'json')
			});

			jQuery('#btn_login').on('click', function() {
				var params = jQuery('#form_login').serializeArray();
				jQuery.post("{% url 'account:login' %}", params, function(data) {
					if(data['status'] == 200) {
						jQuery('#dialog_login').modal('hide');
						window.location.replace('/');
						// swal({
						// 	title: "登录成功",
						// 	text: "",
						// 	type: "success",
						// 	confirmButtonText: "确定"
						// });
					} else if(data['status'] == 400) {
						var errors = [];
						jQuery.each(data['errors'], function(key, value) {
							errors.push(value[0]['message']);
						});
						swal({
							title: "验证失败",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if(data['status'] == 401) {
						var errors = data['errors'] || [];
						swal({
							title: "用户未登录",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if (data['status'] == 500) {
						var errors = data['errors'] || [];
						swal({
							title: "服务器错误",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else {

					}
				}, 'json');
			});

			jQuery('#btn_reset_password').on('click', function() {
				window.location.replace("{% url 'account:reset_password' %}");
			});

			jQuery('#btn_password').on('click', function() {
				var params = jQuery('#form_password').serializeArray();
				jQuery.post("{% url 'account:change_password' %}", params, function(data) {
					if(data['status'] == 200) {
						jQuery('#dialog_password').modal('hide');
						swal({
							title: "修改密码成功, 请重新登陆",
							text: "",
							type: "success",
							confirmButtonText: "确定",
							closeOnConfirm: false,
						}, function() {
							swal.close();
							window.location.replace(window.location.href)
						});
					} else if(data['status'] == 400) {
						var errors = [];
						jQuery.each(data['errors'], function(key, value) {
							errors.push(value[0]['message']);
						});
						swal({
							title: "验证失败",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if(data['status'] == 401) {
						var errors = data['errors'] || [];
						swal({
							title: "用户未登录",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else if (data['status'] == 500) {
						var errors = data['errors'] || [];
						swal({
							title: "服务器错误",
							text: errors.join('\n'),
							type: "error",
							confirmButtonColor: "#DD6B55",
							confirmButtonText: "确定"
						});
					} else {

					}
				}, 'json')
			});

		});
        {% block js %}{% endblock %}
	</script>
</body>
</html>