mage05/28/server/cmdb/agent/urls.py
#encoding: utf-8


from django.conf.urls import url

from .views import ClientListView, ResourceView

app_name = 'agent'

urlpatterns = [
    url('^client/$', ClientListView.as_view(), name='client'),
    url('^client/(?P<uuid>\w{32,64})/resource/$', ResourceView.as_view(), name='resource'),
]

mage05/28/server/cmdb/api/urls.py
#encoding: utf-8

from django.conf.urls import url


from api.views import v1, v2, v3

app_name = 'api'

urlpatterns = [
    url(r'^v1/client/(?P<uuid>\w{32,64})/$', v1.ClientView.as_view()),
    url(r'^v1/heartbeat/(?P<uuid>\w{32,64})/$', v1.HeartbeatView.as_view()),
    url(r'^v1/resource/(?P<uuid>\w{32,64})/$', v1.ResourceView.as_view()),

    url(r'^v2/client/(?P<uuid>\w{32,64})/$', v2.ClientView.as_view()),
    url(r'^v2/heartbeat/(?P<uuid>\w{32,64})/$', v2.HeartbeatView.as_view()),
    url(r'^v2/resource/(?P<uuid>\w{32,64})/$', v2.ResourceView.as_view()),

    url(r'^v3/client/(?P<uuid>\w{32,64})/$', v3.ClientView.as_view()),
    url(r'^v3/heartbeat/(?P<uuid>\w{32,64})/$', v3.HeartbeatView.as_view()),
    url(r'^v3/resource/(?P<uuid>\w{32,64})/$', v3.ResourceView.as_view()),

]

mage05/28/server/cmdb/cmdb/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('agent:client')), name='index'),
    url(r'^api/', include('api.urls')),
    url(r'^agent/', include('agent.urls')),
]

mage05/28/server/cmdb/agent/models.py
#encoding: utf-8

import logging
import traceback

from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from datetime import timedelta, datetime

logger = logging.getLogger(__name__)

class BaseAttrDictMixin(object):

    def as_dict(self):
        _dict = {}
        for _key, _value in self.__dict__.items():
            if type(_value) in [int, float, str, bytes, bool, list, tuple, datetime]:
                _dict[_key] = _value
        return _dict


class Client(BaseAttrDictMixin, models.Model):
    STATUS_OK = 0
    STATUS_DELETE = 1

    uuid = models.CharField(max_length=64, unique=True, default='')
    hostname = models.CharField(max_length=128, default='')
    ip = models.GenericIPAddressField(default='0.0.0.0')
    mac = models.CharField(max_length=64, default='')
    platform = models.CharField(max_length=256, default='')
    arch = models.CharField(max_length=16, default='')
    cpu = models.IntegerField(default=0)
    mem = models.BigIntegerField(default=0)

    pid = models.IntegerField(default=0)
    time = models.FloatField(default=0)

    user = models.CharField(max_length=256, default='')
    application = models.CharField(max_length=256, default='')
    addr = models.CharField(max_length=256, default='')
    remark = models.CharField(max_length=512, default='')

    heartbeat_time = models.DateTimeField(auto_now_add=True)

    register_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)
    status = models.IntegerField(default=0)

    @property
    def is_online(self):
        return timezone.now() - self.heartbeat_time < timedelta(minutes=5)

    @classmethod
    def register(cls, uuid, **kwargs):
        _instance = None
        _created = False
        try:
            _instance = cls.objects.get(uuid=uuid)
        except ObjectDoesNotExist as e:
            _instance = cls()
            setattr(_instance, 'uuid', uuid)
            _created = True

        for _key, _value in kwargs.items():
            if hasattr(_instance, _key):
                setattr(_instance, _key, _value)

        _instance.status = cls.STATUS_OK
        _instance.save()
        return _instance, _created

    @classmethod
    def heartbeat(cls, uuid):
        try:
            _instance = cls.objects.get(uuid=uuid)
            _instance.heartbeat_time = timezone.now()
            _instance.save()
        except ObjectDoesNotExist as e:
            logger.error(e)



class Resource(BaseAttrDictMixin, models.Model):
    uuid = models.CharField(max_length=64, default='')
    time = models.DateTimeField(auto_now_add=True)
    cpu = models.FloatField(default=0)
    mem = models.FloatField(default=0)

    @classmethod
    def create(cls, uuid, **kwargs):
        _instance = cls()
        setattr(_instance, 'uuid', uuid)
        for _key, _value in kwargs.items():
            if hasattr(_instance, _key):
                setattr(_instance, _key, _value)

        _instance.save()
        return _instance

mage05/28/server/cmdb/agent/views.py
#encoding: utf-8

from django.shortcuts import render
from django.views.generic import View, ListView

from django.http import JsonResponse

from .models import Client, Resource

class ClientListView(ListView):
    template_name = 'agent/client.html'
    model = Client


class ResourceView(View):
    SIZE = 180

    def get(self, request, *args, **kwargs):
        _uuid = kwargs.get('uuid')
        _resources = Resource.objects.filter(uuid=_uuid).order_by('-time')[:self.SIZE]
        _resources = [_resource.as_dict() for _resource in _resources]
        return JsonResponse({'code' : 200, 'text' : '', 'result' : _resources})

mage05/28/server/cmdb/agent/templates/agent/client_list.html
{% extends 'base.html' %}

{% block container %}
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th class="col-md-2">主机名</th>
            <th class="col-md-1">IP地址</th>
            <th class="col-md-2">平台</th>
            <th>CPU</th>
            <th>内存</th>
            <th class="col-md-1">用户</th>
            <th class="col-md-1">应用</th>
            <th class="col-md-2">地址</th>
            <th class="col-md-1">备注</th>
            <th class="col-md-1">操作</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object_list %}
            <tr>
                <td>
                    {% if not obj.is_online %}
                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                    {% endif %}
                    {{ obj.hostname }}
                </td>
                <td>{{ obj.ip }}</td>
                <td>{{ obj.platform }}/{{ obj.arch }}</td>
                <td>{{ obj.cpu }}核</td>
                <td>{{ obj.mem|filesizeformat }}</td>
                <td>{{ obj.user }}</td>
                <td>{{ obj.application }}</td>
                <td>{{ obj.addr }}</td>
                <td>{{ obj.remark }}</td>
                <td>
                    <a data-toggle="modal" data-target="#client" data-backdrop="static">编辑</a>
                    <a data-toggle="modal" data-target="#resource" data-backdrop="static" data-url="{% url 'agent:resource' obj.uuid %}">监控</a>
                    <a data-toggle="modal" data-target="#event" data-backdrop="static">告警</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block dialog %}
<div class="modal fade" id="resource" tabindex="-1" role="dialog" aria-labelledby="resource">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div id="resource-panel" style="width: 600px;height:400px;"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="client" tabindex="-1" role="dialog" aria-labelledby="resource">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
             <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">编辑</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="user" class="col-sm-2 control-label">用户</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="user" name="user" placeholder="用户" value="kk" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="application" class="col-sm-2 control-label">应用</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="application" name="application" placeholder="应用" value="MySQL数据库" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="addr" class="col-sm-2 control-label">位置</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="addr" name="addr" placeholder="位置" value="北京市-海淀机房-一机架" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="remark" class="col-sm-2 control-label">备注</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="remark" name="remark" placeholder="备注" value="" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="button" class="btn btn-primary">保存</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="event" tabindex="-1" role="dialog" aria-labelledby="event">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">最近20条告警</h4>
            </div>
            <div class="modal-body">
                <table class="table table-bordered table-hover table-striped table-condensed">
                    <thead>
                        <tr>
                            <th>时间</th>
                            <th>内容</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>2017-10-27 22:49:00</td>
                            <td>连续3分钟CPU使用率超过80%</td>
                        </tr>
                        <tr>
                            <td>2017-10-27 02:49:00</td>
                            <td>连续3分钟内存使用率超过80%</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
jQuery(document).ready(function() {
    var th = null;
    var chart = echarts.init(document.getElementById('resource-panel'));
    var option = {
        title: {
            text: 'CPU、内存监控'
        },
        tooltip: {
            trigger: 'axis',
            formatter: function (params) {
                var name = null, tips = [];
                jQuery.each(params, function(index, value) {
                    name = value['name'];
                    tips.push(value['seriesName'] + ':' + value['value'] + '%');
                });
                return name + '<br/>' + tips.join('<br/>');
            },
            axisPointer: {
                animation: false
            }
        },
        legend: {
            data:['CPU', '内存']
        },
        xAxis: {
            data: []
        },
        yAxis: {
            'max' : 100
        },
        series: []
    };
    function reload(url) {
        jQuery.get(url, function(response) {
            if(response['code'] != 200) {
                return;
            }
            var _xAxis_data = [];
            var _cpu_data = [];
            var _mem_data = [];
            jQuery.each(response['result'], function(index, value) {
                _xAxis_data.unshift(value['time']);
                _cpu_data.unshift(value['cpu']);
                _mem_data.unshift(value['mem']);
            });
            option['xAxis'] = {'data' : _xAxis_data};
            option['series'] = [
                {name: '内存', type:'line', data:_mem_data},
                {name: 'CPU', type:'line', data:_cpu_data},
            ];
            chart.setOption(option);        
        }, 'json');
    }

    jQuery('#resource').on('show.bs.modal', function (e) {
        var target = jQuery(e.relatedTarget);
        var url = target.data('url');
        reload(url);
        th = setInterval(function() {
            reload(url);
        }, 10 * 1000)
    });

    jQuery('#resource').on('hide.bs.modal', function (e) {
        if(th) {
            clearInterval(th);
            th = null;
        }
    });
});


{% endblock %}